### PR TITLE
Automated builds

### PR DESCRIPTION
**Pull request by austinpray**
- Simplifies the dockerfile (using [an image I maintain](https://hub.docker.com/r/austinpray/python-node/) lol)
- Basic e2e test
- Automated builds using travis 

If you set up travis properly and set up your hub.docker.com account people will now be able to do `docker run -d -p 3000:3000 algram/ytdl-webserver` without cloning this repo first. You can also set up daily cron jobs on travis to keep youtube-dl up-to-date on the image https://docs.travis-ci.com/user/cron-jobs/

You need the following env vars in travis https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

- DOCKER_TAG = algram/ytdl-webserver
- DOCKER_USERNAME = algram but it depends on what you set up at hub.docker.com
- DOCKER_PASSWORD = whatever password for hub.docker.com

You can try it yourself https://hub.docker.com/r/austinpray/ytdl-webserver/

`docker run -d -p 3000:3000 austinpray/ytdl-webserver`

### CODE REVIEW

**Comment by c-ascha** [comment]
hey, thank you. the docker container stays not up:
error:
```
docker@test:~ $ docker run -d -p 3000:3000 austinpray/ytdl-webserver
8d4351df1d32187a5fac50de5f05fca1b1bf79bab66589aecf987903348b4241                                                                                                                                                     
docker@test:~ $ docker logs 8d4351df1d32187a5fac50de5f05fca1b1bf79bab66589aecf987903348b4241                                                                                                                  
standard_init_linux.go:190: exec user process caused "exec format error"
```

thank you

**Comment by Algram** [comment]
Perfect, I will set up the Accounts and travis-ci today!

**Comment by c-ascha** [comment]
awesome, thank you!

**Comment by mauritsvdvijgh** [comment]
Made a PR on top of the current state of this one (not sure what the best way to handle that is). It adds a small run only webapp build which is lighter than this one. Which makes sense imho if you add automatic builds and running without cloning the repo/building the image.

**Comment by Algram** [comment]
I will not merge the Dockerfile changes in this PR right now since I'd like for us to try the Alpine approach @mauritsvdvijgh mentioned. I will merge the CI stuff though, thanks a ton!

**Pull request merged**
