### PR TITLE
Update dependencies (upgrade all package)

### PR DESCRIPTION
**Pull request by thangl3**
I have been implemented for update dependencies and upgrade all package
Following the issue [https://github.com/Algram/ytdl-webserver/issues/8](here)

I commented on my commit, and you can check my work base on here: 
[https://futurestud.io/tutorials/hapi-v17-upgrade-guide-your-move-to-async-await](https://futurestud.io/tutorials/hapi-v17-upgrade-guide-your-move-to-async-await)
[https://reactjs.org/](https://reactjs.org)
[https://github.com/babel/babel-loader](https://github.com/babel/babel-loader)
[https://webpack.js.org/concepts/](https://webpack.js.org/concepts/)
[https://hapijs.com/api](https://hapijs.com/api)
and
[https://hapijs.com/tutorials/serving-files](https://hapijs.com/tutorials/serving-files)

So when you testing you maybe make the problem with youtube-dl.exe in `node_modules/youtube-dl/bin` you can fix it with the issue has been logged [https://github.com/przemyslawpluta/node-youtube-dl/issues/215](here).

I tested on front-end and backend, it works.

### CODE REVIEW

**Comment by Algram** [comment]
Hi, thanks a lot for your work. I checked out your changes and I am having the problem that the dev server `npm run dev` does not download videos anymore. Could you check that out?

**Comment by thangl3** [comment]
Yeah, I understood your problem. Actually, this problem from here (I have written an issue about it) [https://github.com/Algram/ytdl-webserver/issues/27](https://github.com/Algram/ytdl-webserver/issues/27) and you should fix it with the way from here [https://github.com/przemyslawpluta/node-youtube-dl/issues/215#issuecomment-426420390](https://github.com/przemyslawpluta/node-youtube-dl/issues/215#issuecomment-426420390).
It's not shown error on the console because of this problem from out of library `node-youtube-dl`.

Now, I'm thinking the way fixing it on the server because the server will call `npm` installs packages each time when we deployed. I'm not yet thinking to the best way to fix it. But on the development mode, you can do it for see the result.

Just download youtube-dl.exe newly from [https://rg3.github.io/youtube-dl/download.html](https://rg3.github.io/youtube-dl/download.html) copy it to folder node_modules/youtube-dl/bin (override old youtube-dl.exe). It will be working.

Besides, when testing it on the same local (localhost) maybe server returns a response with status code 200 but not display button download. Because of the response from http://localhost/download has been blocked by CORS policy. You can fix it with `Access-Control-Access-Origin: *` or install this extension [https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi) on your browser.

**Comment by thangl3** [comment]
I have installed your project on Heroku, and It hasn't worked because of [https://github.com/Algram/ytdl-webserver/issues/27](https://github.com/Algram/ytdl-webserver/issues/27), it does not download videos anymore.
If you any idea we can show it and resolving this problem.

**Comment by Algram** [comment]
Fixed by https://github.com/Algram/ytdl-webserver/commit/7dd8a049b930f7f21bb8064495fc65e4222f558a and https://github.com/Algram/ytdl-webserver/commit/036a1ee935233080f6843f222f7d35ec03be86d8

If you have a suggestion regarding the dev build youtube download working, feel free to open a new PR!

**Pull request closed without merging**
